from app.models.colaborador import Colaborador
from app.models.medicao import Medicao
from app.models.condicao_saude import CondicaoSaude
from app.models.preferencia_alimentar import PreferenciaAlimentar
from app.models.plano_nutricional import PlanoNutricional
from app.models.cardapio import Cardapio
from app.models.refeicao_log import RefeicaoLog
from app.models.alerta_medico import AlertaMedico
from app.models.conversa import ConversaAgente
